# What do I do?
train: False

# data dependencies
ticks_file: '../../data/100.csv'
encoding: 'colh'
delimiter: '|'
cse_file: '../../data/ibex1hr3y.cse'
columns: ['tickopenprice', 'tickmaxprice', 'tickminprice', 'tickcloseprice']
cse_colnames: ['body', 'open', 'high', 'low', 'close']
ohlc_tags: ['o', 'h', 'l', 'c']
cse_tags: ['b', 'o', 'h', 'l', 'c']
log_level: 3
names: ['body', 'move']
model_filename: { body: '../../networks/body_20181016_1400_ibex1hr3y_w3_e100_a0.4518', move: './move_20181014_1115_pibex_1hr_1y_w3_e100_a0.4207' }

# dataset parameters
# num_categories: 26

# training parameters
loss: 'mean_squared_error'
optimizer: 'adam'
metrics: ['accuracy']
epochs: 100
batch_size: 10
window_size: 3
validation_split: 0.1
test_size: 0.1
verbose: 1
num_predictions: 1

# model parameters
l1units: 256
l2units: 256
activation: 'tanh'
dropout: 0.2

# training parameters
epocs: 100
batch_size: 10
validation_split: 0.1
verbose: 1
