# What do I do?
train: False
predict: False

# Log level: 0: Silent, 1: Errors only, 2: Warnings too, 3: info, 4: debug
log_level: 2

# data dependencies
ticks_file: '../../data/ibex1hr1y.csv'
encoding: 'colh'
delimiter: '|'
columns: ['tickopenprice', 'tickmaxprice', 'tickminprice', 'tickcloseprice']
cse_colnames: ['body', 'open', 'high', 'low', 'close']
ohlc_tags: ['o', 'h', 'l', 'c']
cse_tags: ['b', 'o', 'h', 'l', 'c']

# The max length of ticks to be received vi API.
max_tick_series_length: 10

# Files, Networks, Names...
models_dir: '../../networks'
subtypes: ['body', 'move']
model_names:
  1yw7:
    body: body_20181027_2247_ibex1hr1y_w7_e100_a0.5092
    move: move_20181027_2314_ibex1hr1y_w7_e100_a0.4020
    encoder: encoder_ibex1hr1y_w7
  5yw7:
    body: body_20181028_0954_ibex1hr5y_w7_e100_a0.5014
    move: move_20181028_1040_ibex1hr5y_w7_e100_a0.4104
    encoder: encoder_ibex1hr5y_w7
  10yw7:
    body: body_20181028_1705_ibex1hr10y_w7_e100_a0.4747
    move: move_20181028_1849_ibex1hr10y_w7_e100_a0.4233
    encoder: encoder_ibex1hr10y_w7

# training parameters
loss: 'mean_squared_error'
optimizer: 'adam'
metrics: ['accuracy']
epochs: 100
batch_size: 10
window_size: 3
validation_split: 0.1
test_size: 0.1
verbose: 1
num_predictions: 1

# model parameters
l1units: 256
l2units: 256
activation: 'tanh'
dropout: 0.1
