file_path: '~/Documents/SideProjects/sailboatsfactory/data/ibex_hourly_1y_rounded.csv'

scaler: MinMaxScaler(feature_range=(0, 1))

lstm_stateful: True
lstm_shuffle: False
lstm_loss: 'mae'
lstm_optimizer: 'rmsprop'

#lstm_neurons: 50
lstm_num_epochs: 20
lstm_batch_size: 10
lstm_timesteps: 10
lstm_predictions: 1

lstm_numlayers: 2
lstm_dropout1: 0.1
lstm_dropout2: 0.1
lstm_layer1: 128
lstm_layer2: 128


validation_ratio: 0.05
diff_intervals: 1
#look_back: 2
#look_forward: 1
#test_numbatches: 1
num_testcases: 50

keras_verbose_level: 1
delimiter: '|'
columNames:
  - tickcloseprice
#  - tickopenprice
#  - tickminprice
#  - tickmaxprice
  - tickvolume
  - awesome
  - macd
  - rsi
#  - rsi2
  - exponentialmovingaverage
  - moneyflowindicator
#  - moneyflowindicator2
  - bollingermid
#  - bollingerlow
#  - bollingerupper
  - stochastick
#  - stochasticd
  - stochasticrsi
  - positivevolumeindex
  - negativevolumeindex
  - volumeweightedaverageprice
#  - dailytime
  - weeklytime
#  - monthlytime
