project_path: 'Documents/SideProjects/sailboatsfactory'
data_path: 'data'
networks_path: 'networks'
training_file: 'ibex_1hr_5y.csv'

# If specified, a model is loaded instead of being created. Same with weights
load_model: ''
load_weights: ''

# if specified, the weights are saved into 'networks_path'. Same with weights.
save_model: True
save_weights: True
save_predictor: True

# Prediction Parameters
pred_model: 'model_name_pred.json'
pred_weights: 'weights.h5'
pred_dataset: 'ibex_1hr_5y.csv'
num_saturations: 1

# dataset preparation
prepare_normalize: True

num_testcases: 100
validation_ratio: 0.05
diff_intervals: 1

# LSTM configuration
lstm_stateful: True
lstm_shuffle: True
lstm_forget_bias: False
lstm_unroll: False
lstm_loss: 'mse'
lstm_optimizer: 'rmsprop'

lstm_num_epochs: 10
lstm_batch_size: 10
lstm_timesteps: 6
lstm_predictions: 1

lstm_numlayers: 2
lstm_layer1: 32
lstm_dropout1: 0.1
lstm_layer2: 64
lstm_dropout2: 0.1

keras_verbose_level: 1
delimiter: '|'
columNames:
  - tickcloseprice
#  - tickopenprice
#  - tickminprice
#  - tickmaxprice
#  - tickvolume
#  - awesome
#  - macd
#  - positivevolumeindex
#  - negativevolumeindex
