project_path: 'Documents/SideProjects/sailboatsfactory'
data_path: 'data'
networks_path: 'networks'
training_file: 'ibex_1hr_5y.csv'

# If specified, a model is loaded instead of being created. Same with weights
load_model: ''
load_weights: ''

# if specified, the weights are saved into 'networks_path'. Same with weights.
save_model: No
save_weights: No
save_predictor: False

# Prediction Parameters
pred_model: 'model_name_pred.json'
pred_weights: 'weights.h5'
pred_dataset: 'ibex_1hr_5y.csv'
num_saturations: 1

# dataset preparation
prepare_normalize: True
num_testcases: 100
diff_intervals: 1

# LSTM configuration
lstm_stateful: True
lstm_shuffle: True
lstm_forget_bias: False
lstm_unroll: False
lstm_loss: 'mse'
lstm_optimizer: 'rmsprop'

lstm_num_epochs: 80
lstm_batch_size: 48
lstm_timesteps: 24
lstm_predictions: 1

lstm_numlayers: 1
lstm_layer1: 128
lstm_dropout1: 0.075

keras_verbose_level: 0
delimiter: '|'
columNames:
  - tickcloseprice
  - tickopenprice
  - tickminprice
  - tickmaxprice
  - tickvolume
#  - awesome
#  - macd
#  - positivevolumeindex
#  - negativevolumeindex
#  - rsi
#  - rsi2
#  - exponentialmovingaverage
#  - moneyflowindicator
#  - moneyflowindicator2
#  - bollingermid
#  - bollingerlow
#  - bollingerupper
#  - stochastick
#  - stochasticd
#  - stochasticrsi
#  - volumeweightedaverageprice
#  - dailytime
#  - weeklytime
#  - monthlytime
#  - coppockcurve
#  - avgdirmov
#  - dirmovminus
#  - dirmovplus
#  - chaikinmoneyflow
